# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Pull Request

on:
  pull_request:
    branches: [ 3.x ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Set up JDK 8
      uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
      with:
        distribution: 'zulu'
        java-version: '8'
    - name: Cache Gradle packages
      uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-1-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle-1-
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build RxJava
      run: ./gradlew build --stacktrace
    - name: Upload to Codecov  
      uses: codecov/codecov-action@1e68e06f1dbfde0e4cefc87efeba9e4643565303 # v5.1.2
    - name: Generate Javadoc
      run: ./gradlew javadoc --stacktrace
